# Generated by Django 5.2.5 on 2025-08-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Smart Phones', 'Smart Phones'), ('Fashion', 'Fashion'), ('Interior Design', 'Interior Design'), ('Laptops', 'Laptops')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
