# Generated by Django 5.2.5 on 2025-08-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=255)),
                ("category", models.TextField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity", models.PositiveIntegerField()),
                ("color", models.CharField(max_length=30)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="product/"),
                ),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
