# Generated by Django 5.2.4 on 2025-08-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('smart_phones', 'Smart Phones'), ('fashion', 'Phones'), ('interior_design', 'Interior Design'), ('laptops', 'Laptops')], max_length=255)),
                ('price', models.PositiveBigIntegerField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
